/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kclass;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Aji Putra Pamungkas
 */
public class LayoutPengguna extends javax.swing.JFrame {

    /**
     * Creates new form LayoutPengguna
     */
    JLabel[] arrLabel;
    JButton[] arrButton;
    JTextField[] arrTF;
    Connection conn;
    String idSession;
    PreparedStatement ps;
    public static LayoutPengguna instanceLP;


    public LayoutPengguna(String idSession, String username) {
        this.setLocationRelativeTo(null);
        this.setSize(800, 600);
        initComponents();
        initDB();
        namaUser.setText(username);
        this.idSession = idSession;
        instanceLP = this;    
        try {
            ps = conn.prepareStatement("SELECT score FROM kScore WHERE idUser = ? AND idCSV = ?");
        } catch (SQLException ex) {
            Logger.getLogger(LayoutPengguna.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshList();       
    }
    
    public void handleFromKuis(String score, String idCSV){
        try {
            ps.setString(1,idSession); ps.setString(2,idCSV);
            ResultSet rs = ps.executeQuery();
            if (rs.next()){ //ada
                int skorDB = rs.getInt("score");
                if(Integer.parseInt(score) > skorDB){
                    PreparedStatement ps2 = conn.prepareStatement("UPDATE kScore SET score = ? WHERE idUser = ? AND idCSV = ?");
                    ps2.setString(1, score); ps2.setString(2, idSession); ps2.setString(3, idCSV);
                    ps2.executeUpdate();
                    ps2.close();
                }       
            } else{           //tidak ada 
                PreparedStatement ps2 = conn.prepareStatement("INSERT INTO kScore VALUES (?,?,?)");
                ps2.setString(1, idSession); ps2.setString(2, idCSV); ps2.setString(3, score);
                ps2.executeUpdate();
                ps2.close();
            }
            rs.close();
            refreshList();
        } catch (SQLException ex) {
            Logger.getLogger(LayoutPengguna.class.getName()).log(Level.SEVERE, null, ex);
        }
    };
    
    private void refreshList(){
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM kCSV");
            
            ps.setString(1,idSession);
            int totalSkor = 0;
            int totalPengerjaan = 0;
            int totalKuis = 0;
            int i = 0;
            while(rs.next()){
                int idCSV = rs.getInt("idCSV");
                String nama = rs.getString("nama");
                arrLabel[i].setText("Kuis " + idCSV + " : " + nama);
                arrButton[i].setEnabled(true);
                
                ps.setString(2,String.valueOf(idCSV));
                ResultSet rsLoop = ps.executeQuery();
                if(rsLoop.next()){
                    arrButton[i].setText("Reattempt");
                    arrTF[i].setText("Nilai: " + rsLoop.getInt("score"));
                    totalSkor += rsLoop.getInt("score");
                    totalPengerjaan++;
                }
                else{
                    arrButton[i].setText("Attempt");
                    arrTF[i].setText("Nilai: ");
                }
                totalKuis++;
                rsLoop.close();
                
                i++;
            }
            for(int j = i; j <10; j++){
                arrLabel[j].setText("Kuis : ");
                arrButton[j].setEnabled(false);
                arrTF[j].setText("Nilai: ");
            }
            rs.close();
            
            jProgressBar1.setValue(totalPengerjaan*100/totalKuis);
            nilaiRata.setText(Double.toString(totalSkor*1.0/totalPengerjaan));
            
        } catch (SQLException ex) {
            Logger.getLogger(LayoutPengguna.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupOpsi = new javax.swing.ButtonGroup();
        grupPGIsian = new javax.swing.ButtonGroup();
        StatusUser = new javax.swing.JPanel();
        blankpp = new javax.swing.JLabel();
        blankpp.setHorizontalAlignment(JLabel.CENTER);
        namaUser = new javax.swing.JLabel();
        namaUser.setHorizontalAlignment(JLabel.CENTER);
        labelStatus = new javax.swing.JLabel();
        labelRata = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        buttonLogout = new javax.swing.JButton();
        nilaiRata = new javax.swing.JLabel();
        labelRata1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        parentPanel = new javax.swing.JPanel();
        dashboardTugas = new javax.swing.JPanel();
        labelList = new javax.swing.JLabel();
        labelK0 = new javax.swing.JLabel();
        labelK1 = new javax.swing.JLabel();
        labelK2 = new javax.swing.JLabel();
        labelK3 = new javax.swing.JLabel();
        labelK4 = new javax.swing.JLabel();
        labelK5 = new javax.swing.JLabel();
        labelK6 = new javax.swing.JLabel();
        labelK7 = new javax.swing.JLabel();
        labelK8 = new javax.swing.JLabel();
        labelK9 = new javax.swing.JLabel();
        arrLabel = new JLabel[10];
        arrLabel[0] = labelK0;
        arrLabel[1] = labelK1;
        arrLabel[2] = labelK2;
        arrLabel[3] = labelK3;
        arrLabel[4] = labelK4;
        arrLabel[5] = labelK5;
        arrLabel[6] = labelK6;
        arrLabel[7] = labelK7;
        arrLabel[8] = labelK8;
        arrLabel[9] = labelK9;
        attemptK0 = new javax.swing.JButton();
        nilaiK0 = new javax.swing.JTextField();
        attemptK1 = new javax.swing.JButton();
        attemptK2 = new javax.swing.JButton();
        attemptK3 = new javax.swing.JButton();
        attemptK4 = new javax.swing.JButton();
        attemptK5 = new javax.swing.JButton();
        attemptK6 = new javax.swing.JButton();
        attemptK7 = new javax.swing.JButton();
        attemptK8 = new javax.swing.JButton();
        attemptK9 = new javax.swing.JButton();
        arrButton = new JButton[10];
        arrButton[0] = attemptK0;
        arrButton[1] = attemptK1;
        arrButton[2] = attemptK2;
        arrButton[3] = attemptK3;
        arrButton[4] = attemptK4;
        arrButton[5] = attemptK5;
        arrButton[6] = attemptK6;
        arrButton[7] = attemptK7;
        arrButton[8] = attemptK8;
        arrButton[9] = attemptK9;
        nilaiK1 = new javax.swing.JTextField();
        nilaiK2 = new javax.swing.JTextField();
        nilaiK3 = new javax.swing.JTextField();
        nilaiK4 = new javax.swing.JTextField();
        nilaiK5 = new javax.swing.JTextField();
        nilaiK6 = new javax.swing.JTextField();
        nilaiK7 = new javax.swing.JTextField();
        nilaiK8 = new javax.swing.JTextField();
        nilaiK9 = new javax.swing.JTextField();
        arrTF = new JTextField[10];
        arrTF[0] = nilaiK0;
        arrTF[1] = nilaiK1;
        arrTF[2] = nilaiK2;
        arrTF[3] = nilaiK3;
        arrTF[4] = nilaiK4;
        arrTF[5] = nilaiK5;
        arrTF[6] = nilaiK6;
        arrTF[7] = nilaiK7;
        arrTF[8] = nilaiK8;
        arrTF[9] = nilaiK9;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("K Class - Pengguna");

        StatusUser.setBackground(new java.awt.Color(0, 51, 51));
        StatusUser.setBorder(new javax.swing.border.MatteBorder(null));
        StatusUser.setPreferredSize(new java.awt.Dimension(202, 100));

        blankpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blankpp.png"))); // NOI18N
        blankpp.setMaximumSize(new java.awt.Dimension(162, 162));
        blankpp.setMinimumSize(new java.awt.Dimension(162, 162));

        namaUser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        namaUser.setForeground(new java.awt.Color(255, 255, 255));
        namaUser.setText("MANUSIA");
        namaUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelStatus.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(153, 255, 153));
        labelStatus.setText("Status Pengerjaan");

        labelRata.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelRata.setForeground(new java.awt.Color(255, 255, 255));
        labelRata.setText("Rata-rata Nilai:");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 50));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 50));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 50));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 50));

        buttonLogout.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        nilaiRata.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nilaiRata.setForeground(new java.awt.Color(0, 255, 0));
        nilaiRata.setText("100");

        labelRata1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelRata1.setForeground(new java.awt.Color(255, 255, 255));
        labelRata1.setText("Progress:");

        jProgressBar1.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setForeground(new java.awt.Color(153, 255, 153));
        jProgressBar1.setValue(100);
        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout StatusUserLayout = new javax.swing.GroupLayout(StatusUser);
        StatusUser.setLayout(StatusUserLayout);
        StatusUserLayout.setHorizontalGroup(
            StatusUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(StatusUserLayout.createSequentialGroup()
                .addGroup(StatusUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusUserLayout.createSequentialGroup()
                        .addGroup(StatusUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StatusUserLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(StatusUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(StatusUserLayout.createSequentialGroup()
                                        .addComponent(labelRata)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nilaiRata))
                                    .addGroup(StatusUserLayout.createSequentialGroup()
                                        .addComponent(labelRata1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(StatusUserLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(buttonLogout)))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addComponent(namaUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(StatusUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(blankpp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        StatusUserLayout.setVerticalGroup(
            StatusUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusUserLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(blankpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaUser)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StatusUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRata)
                    .addComponent(nilaiRata))
                .addGap(10, 10, 10)
                .addGroup(StatusUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelRata1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(buttonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parentPanel.setLayout(new java.awt.CardLayout());

        dashboardTugas.setBackground(new java.awt.Color(0, 102, 102));

        labelList.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelList.setForeground(new java.awt.Color(255, 255, 255));
        labelList.setText("LIST KUIS");

        labelK0.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK0.setForeground(new java.awt.Color(255, 255, 255));
        labelK0.setText("Kuis 1 :  Provinsi - Ibukota");

        labelK1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK1.setForeground(new java.awt.Color(255, 255, 255));
        labelK1.setText("Kuis 2 : ");

        labelK2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK2.setForeground(new java.awt.Color(255, 255, 255));
        labelK2.setText("Kuis 3 : ");

        labelK3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK3.setForeground(new java.awt.Color(255, 255, 255));
        labelK3.setText("Kuis 4 : ");

        labelK4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK4.setForeground(new java.awt.Color(255, 255, 255));
        labelK4.setText("Kuis 5 : ");

        labelK5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK5.setForeground(new java.awt.Color(255, 255, 255));
        labelK5.setText("Kuis 6 : ");

        labelK6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK6.setForeground(new java.awt.Color(255, 255, 255));
        labelK6.setText("Kuis 7 : ");

        labelK7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK7.setForeground(new java.awt.Color(255, 255, 255));
        labelK7.setText("Kuis 8 : ");

        labelK8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK8.setForeground(new java.awt.Color(255, 255, 255));
        labelK8.setText("Kuis 9 : ");

        labelK9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelK9.setForeground(new java.awt.Color(255, 255, 255));
        labelK9.setText("Kuis 10 : ");

        attemptK0.setBackground(new java.awt.Color(204, 204, 255));
        attemptK0.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK0.setText("Attempt");
        attemptK0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK0ActionPerformed(evt);
            }
        });

        nilaiK0.setText("Nilai: ");
        nilaiK0.setEnabled(false);
        nilaiK0.setFocusable(false);
        nilaiK0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK0ActionPerformed(evt);
            }
        });

        attemptK1.setBackground(new java.awt.Color(204, 204, 255));
        attemptK1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK1.setText("Attempt");
        attemptK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK1ActionPerformed(evt);
            }
        });

        attemptK2.setBackground(new java.awt.Color(204, 204, 255));
        attemptK2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK2.setText("Attempt");
        attemptK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK2ActionPerformed(evt);
            }
        });

        attemptK3.setBackground(new java.awt.Color(204, 204, 255));
        attemptK3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK3.setText("Attempt");
        attemptK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK3ActionPerformed(evt);
            }
        });

        attemptK4.setBackground(new java.awt.Color(204, 204, 255));
        attemptK4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK4.setText("Attempt");
        attemptK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK4ActionPerformed(evt);
            }
        });

        attemptK5.setBackground(new java.awt.Color(204, 204, 255));
        attemptK5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK5.setText("Attempt");
        attemptK5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK5ActionPerformed(evt);
            }
        });

        attemptK6.setBackground(new java.awt.Color(204, 204, 255));
        attemptK6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK6.setText("Attempt");
        attemptK6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK6ActionPerformed(evt);
            }
        });

        attemptK7.setBackground(new java.awt.Color(204, 204, 255));
        attemptK7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK7.setText("Attempt");
        attemptK7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK7ActionPerformed(evt);
            }
        });

        attemptK8.setBackground(new java.awt.Color(204, 204, 255));
        attemptK8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK8.setText("Attempt");
        attemptK8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK8ActionPerformed(evt);
            }
        });

        attemptK9.setBackground(new java.awt.Color(204, 204, 255));
        attemptK9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        attemptK9.setText("Attempt");
        attemptK9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptK9ActionPerformed(evt);
            }
        });

        nilaiK1.setText("Nilai: ");
        nilaiK1.setEnabled(false);
        nilaiK1.setFocusable(false);
        nilaiK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK1ActionPerformed(evt);
            }
        });

        nilaiK2.setText("Nilai: ");
        nilaiK2.setEnabled(false);
        nilaiK2.setFocusable(false);
        nilaiK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK2ActionPerformed(evt);
            }
        });

        nilaiK3.setText("Nilai: ");
        nilaiK3.setEnabled(false);
        nilaiK3.setFocusable(false);
        nilaiK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK3ActionPerformed(evt);
            }
        });

        nilaiK4.setText("Nilai: ");
        nilaiK4.setEnabled(false);
        nilaiK4.setFocusable(false);
        nilaiK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK4ActionPerformed(evt);
            }
        });

        nilaiK5.setText("Nilai: ");
        nilaiK5.setEnabled(false);
        nilaiK5.setFocusable(false);
        nilaiK5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK5ActionPerformed(evt);
            }
        });

        nilaiK6.setText("Nilai: ");
        nilaiK6.setEnabled(false);
        nilaiK6.setFocusable(false);
        nilaiK6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK6ActionPerformed(evt);
            }
        });

        nilaiK7.setText("Nilai: ");
        nilaiK7.setEnabled(false);
        nilaiK7.setFocusable(false);
        nilaiK7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK7ActionPerformed(evt);
            }
        });

        nilaiK8.setText("Nilai: ");
        nilaiK8.setEnabled(false);
        nilaiK8.setFocusable(false);
        nilaiK8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK8ActionPerformed(evt);
            }
        });

        nilaiK9.setText("Nilai: ");
        nilaiK9.setEnabled(false);
        nilaiK9.setFocusable(false);
        nilaiK9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiK9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardTugasLayout = new javax.swing.GroupLayout(dashboardTugas);
        dashboardTugas.setLayout(dashboardTugasLayout);
        dashboardTugasLayout.setHorizontalGroup(
            dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTugasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK0, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nilaiK0, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiK2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiK3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiK4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiK5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK6, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiK6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK7, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiK7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK8, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiK8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK9, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiK9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardTugasLayout.createSequentialGroup()
                        .addComponent(labelK1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attemptK1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiK1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dashboardTugasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelList, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 585, Short.MAX_VALUE))
        );
        dashboardTugasLayout.setVerticalGroup(
            dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTugasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelList)
                .addGap(18, 18, 18)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK0, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK0)
                    .addComponent(nilaiK0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK1)
                    .addComponent(nilaiK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK2)
                    .addComponent(nilaiK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK3)
                    .addComponent(nilaiK3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK4)
                    .addComponent(nilaiK4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK5)
                    .addComponent(nilaiK5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK6)
                    .addComponent(nilaiK6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK7)
                    .addComponent(nilaiK7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK8)
                    .addComponent(nilaiK8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelK9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptK9)
                    .addComponent(nilaiK9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        parentPanel.add(dashboardTugas, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StatusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StatusUser, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
            .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(770, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void attemptK0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK0ActionPerformed
        // TODO add your handling code here:
        String nama = labelK0.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK0ActionPerformed

    private void attemptK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK1ActionPerformed
        // TODO add your handling code here:
        String nama = labelK1.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK1ActionPerformed

    private void attemptK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK2ActionPerformed
        // TODO add your handling code here:
        String nama = labelK2.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK2ActionPerformed

    private void attemptK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK3ActionPerformed
        // TODO add your handling code here:
        String nama = labelK3.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK3ActionPerformed

    private void attemptK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK4ActionPerformed
        // TODO add your handling code here:
        String nama = labelK4.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK4ActionPerformed

    private void attemptK5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK5ActionPerformed
        // TODO add your handling code here:
        String nama = labelK5.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK5ActionPerformed

    private void attemptK6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK6ActionPerformed
        // TODO add your handling code here:
        String nama = labelK6.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK6ActionPerformed

    private void attemptK7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK7ActionPerformed
        // TODO add your handling code here:
        String nama = labelK7.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK7ActionPerformed

    private void attemptK8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK8ActionPerformed
        // TODO add your handling code here:
        String nama = labelK8.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK8ActionPerformed

    private void attemptK9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptK9ActionPerformed
        // TODO add your handling code here:
        String nama = labelK9.getText();
        int idxAkhir = nama.indexOf(":");
        String idxCSV = nama.substring(4, idxAkhir-1);
        attemptPerformed(idxCSV);
    }//GEN-LAST:event_attemptK9ActionPerformed

    private void attemptPerformed(String idxCSV){
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT url FROM kCSV WHERE idCSV = " + idxCSV);
            if(rs != null && rs.next()){
                String urlKuis = rs.getString("url");
                new LayoutKuis(idxCSV, urlKuis);
            }
            st.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(LayoutPengguna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void nilaiK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK1ActionPerformed

    private void nilaiK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK2ActionPerformed

    private void nilaiK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK3ActionPerformed

    private void nilaiK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK4ActionPerformed

    private void nilaiK5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK5ActionPerformed

    private void nilaiK6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK6ActionPerformed

    private void nilaiK7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK7ActionPerformed

    private void nilaiK8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK8ActionPerformed

    private void nilaiK9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK9ActionPerformed

    private void nilaiK0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiK0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiK0ActionPerformed
    

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        try {
            ps.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(LayoutPengguna.class.getName()).log(Level.SEVERE, null, ex);
        }
        new LayoutLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed
    
    private void initDB() {
        String url = "jdbc:mysql://localhost:3306/kclassDB?useSSL=true";
        String username = "root";
        String password = "adminkurukuru_2";
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Koneksi sukses Layout Login");
        } catch (Exception e){
            System.out.println("Exception: " + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StatusUser;
    private javax.swing.JButton attemptK0;
    private javax.swing.JButton attemptK1;
    private javax.swing.JButton attemptK2;
    private javax.swing.JButton attemptK3;
    private javax.swing.JButton attemptK4;
    private javax.swing.JButton attemptK5;
    private javax.swing.JButton attemptK6;
    private javax.swing.JButton attemptK7;
    private javax.swing.JButton attemptK8;
    private javax.swing.JButton attemptK9;
    private javax.swing.JLabel blankpp;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JPanel dashboardTugas;
    private javax.swing.ButtonGroup grupOpsi;
    private javax.swing.ButtonGroup grupPGIsian;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelK0;
    private javax.swing.JLabel labelK1;
    private javax.swing.JLabel labelK2;
    private javax.swing.JLabel labelK3;
    private javax.swing.JLabel labelK4;
    private javax.swing.JLabel labelK5;
    private javax.swing.JLabel labelK6;
    private javax.swing.JLabel labelK7;
    private javax.swing.JLabel labelK8;
    private javax.swing.JLabel labelK9;
    private javax.swing.JLabel labelList;
    private javax.swing.JLabel labelRata;
    private javax.swing.JLabel labelRata1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel namaUser;
    private javax.swing.JTextField nilaiK0;
    private javax.swing.JTextField nilaiK1;
    private javax.swing.JTextField nilaiK2;
    private javax.swing.JTextField nilaiK3;
    private javax.swing.JTextField nilaiK4;
    private javax.swing.JTextField nilaiK5;
    private javax.swing.JTextField nilaiK6;
    private javax.swing.JTextField nilaiK7;
    private javax.swing.JTextField nilaiK8;
    private javax.swing.JTextField nilaiK9;
    private javax.swing.JLabel nilaiRata;
    private javax.swing.JPanel parentPanel;
    // End of variables declaration//GEN-END:variables
}
