/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kclass;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aji Putra Pamungkas
 */
public class LayoutLogin extends javax.swing.JFrame {

    /**
     * Creates new form LayoutFrame
     */
    Connection conn;
    public LayoutLogin() {
        initDB();
        initComponents();
    }
       
    private void initDB() {
        String url = "jdbc:mysql://localhost:3306/kclassDB?useSSL=true";
        String username = "root";
        String password = "adminkurukuru_2";
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Koneksi sukses Layout Login");
        } catch (Exception e){
            System.out.println("Exception: " + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        labelPembuka2 = new javax.swing.JLabel();
        areausername = new javax.swing.JTextField();
        teksusername = new javax.swing.JLabel();
        tekspassword = new javax.swing.JLabel();
        buttonloginreg = new javax.swing.JButton();
        labelPembuka1 = new javax.swing.JLabel();
        loginreg = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        areapassword = new javax.swing.JPasswordField();
        showpass = new javax.swing.JCheckBox();
        labelKClass = new javax.swing.JLabel();
        deskripsiKClass = new javax.swing.JLabel();
        ppTestimoni = new javax.swing.JLabel();
        hTestimoni = new javax.swing.JLabel();
        testimoni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("K Class");
        setBackground(new java.awt.Color(102, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanelLogin.setBackground(new java.awt.Color(0, 102, 102));
        jPanelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 5));
        jPanelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelPembuka2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelPembuka2.setForeground(new java.awt.Color(255, 255, 255));
        labelPembuka2.setText("Sign in untuk mengakses Dashboard KClass");

        areausername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        areausername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areausernameActionPerformed(evt);
            }
        });
        areausername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                areausernameKeyTyped(evt);
            }
        });

        teksusername.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        teksusername.setForeground(new java.awt.Color(255, 255, 255));
        teksusername.setText("Username");

        tekspassword.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        tekspassword.setForeground(new java.awt.Color(255, 255, 255));
        tekspassword.setText("Password");

        buttonloginreg.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        buttonloginreg.setForeground(new java.awt.Color(0, 102, 102));
        buttonloginreg.setText("Login");
        buttonloginreg.setBorderPainted(false);
        buttonloginreg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonloginreg.setPreferredSize(new java.awt.Dimension(75, 20));
        buttonloginreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonloginregActionPerformed(evt);
            }
        });

        labelPembuka1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelPembuka1.setForeground(new java.awt.Color(255, 255, 255));
        labelPembuka1.setText("Selamat Datang ~");

        loginreg.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        loginreg.setForeground(new java.awt.Color(255, 255, 255));
        loginreg.setText("Tidak punya akun? Sign up disini");
        loginreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginregMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginregMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginregMouseExited(evt);
            }
        });

        warning.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 153, 153));
        warning.setText("Username atau Password tidak ditemukan!");

        areapassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        areapassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                areapasswordKeyTyped(evt);
            }
        });

        showpass.setForeground(new java.awt.Color(255, 255, 255));
        showpass.setText("Tampilkan Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonloginreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                        .addComponent(warning)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                        .addComponent(loginreg)
                        .addGap(135, 135, 135))))
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showpass)
                    .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(teksusername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPembuka1)
                        .addComponent(areausername)
                        .addComponent(tekspassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(areapassword, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                    .addComponent(labelPembuka2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(labelPembuka1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPembuka2)
                .addGap(57, 57, 57)
                .addComponent(teksusername)
                .addGap(10, 10, 10)
                .addComponent(areausername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(tekspassword)
                .addGap(18, 18, 18)
                .addComponent(areapassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showpass)
                .addGap(16, 16, 16)
                .addComponent(buttonloginreg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginreg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warning)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        warning.setVisible(false);

        labelKClass.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        labelKClass.setForeground(new java.awt.Color(0, 51, 51));
        labelKClass.setText("K Class");

        deskripsiKClass.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        deskripsiKClass.setForeground(new java.awt.Color(0, 51, 51));
        deskripsiKClass.setText("Aplikasi kuis sederhana dengan Java");

        ppTestimoni.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ppTestimoni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sigmacart.png"))); // NOI18N
        ppTestimoni.setText("jLabel1");

        hTestimoni.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        hTestimoni.setForeground(new java.awt.Color(0, 102, 102));
        hTestimoni.setText("Testimoni dari Alexander Maguire");

        testimoni.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        testimoni.setForeground(new java.awt.Color(0, 102, 102));
        testimoni.setText("\"Aplikasi ini sangat membantu hidup saya\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deskripsiKClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(ppTestimoni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testimoni)
                            .addComponent(hTestimoni))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelKClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskripsiKClass)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hTestimoni)
                        .addGap(12, 12, 12)
                        .addComponent(testimoni))
                    .addComponent(ppTestimoni))
                .addGap(54, 54, 54))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void areausernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areausernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areausernameActionPerformed

    private void buttonloginregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonloginregActionPerformed
        // TODO add your handling code here:
        if(buttonloginreg.getText().equals("Login")){
            String username = areausername.getText();
            String pw = areapassword.getText();
            if (username.length() == 0 || pw.length() == 0){
                warning.setText("Username atau Password tidak boleh kosong");
                warning.setVisible(true);
                areausername.requestFocus();
                return;
            }
            if (!Character.isLetter(username.charAt(0))){
                warning.setText("Karakter username pertama harus berupa alfabet");
                warning.setVisible(true);
                areausername.requestFocus();
                return;
            }
            try {
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM kUser");
                while(rs.next()){
                    if(username.equals(rs.getString("username")) && pw.equals(rs.getString("pass"))){  
                        String idSession = rs.getString("idUser");
                        rs.close();
                        st.close();
                        conn.close();
                        new LayoutPengguna(idSession,username).setVisible(true);                      
                        this.dispose();
                        break;                  
                    }
                }
                areausername.requestFocus();
                warning.setText("Username atau Password tidak ditemukan!");
                warning.setVisible(true); //kalau tidak ketemu
            } catch (SQLException ex) {
                Logger.getLogger(LayoutLogin.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
        }
        else{
            try{
                PreparedStatement ps = conn.prepareStatement("SELECT * FROM kUser WHERE username = ?");
                ps.setString(1, areausername.getText());
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    warning.setText("Username sudah ada dalam database");
                    warning.setForeground(Color.PINK);
                    warning.setVisible(true);                  
                } else {
                    PreparedStatement ps2 = conn.prepareStatement("INSERT INTO kUser(username, pass) VALUES (?,?)");
                    ps2.setString(1, areausername.getText());
                    ps2.setString(2, areapassword.getText());
                    ps2.executeUpdate();
                    ps2.close();

                    JOptionPane.showConfirmDialog(null, "Username "+ areausername.getText() + " berhasil dibuat", 
                            "Pesan Berhasil", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    
                    buttonloginreg.setText("Login");
                    loginreg.setText("Belum ada akun? Sign up disini");
                }           
                ps.close();
                rs.close();
            } catch(SQLException ex){
                Logger.getLogger(LayoutLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_buttonloginregActionPerformed

    private void loginregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginregMouseClicked
        // TODO add your handling code here:
        if(buttonloginreg.getText().equals("Login")){
            buttonloginreg.setText("Sign up");
            loginreg.setText("Sudah punya akun? Login disini");
        }
        else{ //buttonloginreg = Sign up
            buttonloginreg.setText("Login");
            loginreg.setText("Belum ada akun? Sign up disini");
        }
        
    }//GEN-LAST:event_loginregMouseClicked

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        // TODO add your handling code here:
        if(showpass.isSelected()){
            areapassword.setEchoChar((char)0);
        }
        else{
            areapassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void loginregMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginregMouseEntered
        // TODO add your handling code here:
        loginreg.setForeground(Color.YELLOW);
    }//GEN-LAST:event_loginregMouseEntered

    private void loginregMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginregMouseExited
        // TODO add your handling code here:
        loginreg.setForeground(Color.WHITE);
    }//GEN-LAST:event_loginregMouseExited

    private void areausernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areausernameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isLetterOrDigit(c) && c != '_' && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE){
            evt.consume(); // consume invalid char
        }
    }//GEN-LAST:event_areausernameKeyTyped

    private void areapasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areapasswordKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isLetterOrDigit(c) && c != '_' && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE){
            evt.consume(); // consume invalid char
        }
    }//GEN-LAST:event_areapasswordKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField areapassword;
    private javax.swing.JTextField areausername;
    private javax.swing.JButton buttonloginreg;
    private javax.swing.JLabel deskripsiKClass;
    private javax.swing.JLabel hTestimoni;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JLabel labelKClass;
    private javax.swing.JLabel labelPembuka1;
    private javax.swing.JLabel labelPembuka2;
    private javax.swing.JLabel loginreg;
    private javax.swing.JLabel ppTestimoni;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JLabel tekspassword;
    private javax.swing.JLabel teksusername;
    private javax.swing.JLabel testimoni;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
